In [7]:
import pandas as pd

In [8]:
##GOOD FOR CATEGORICAL DATA -> NUMBERS 
# ONE HOT ->  FOR NOMINAL DATA (colors,types of cars etc)

In [9]:
d = {'sales': [100000,222000,1000000,522000,111111,222222,1111111,20000,75000,90000,1000000,10000],
'city': ['Tampa','Tampa','Orlando','Jacksonville','Miami','Jacksonville','Miami','Miami','Orlando','Orlando','Orlando','Orlando'],
'size': ['Small', 'Medium','Large','Large','Small','Medium','Large','Small','Medium','Medium','Medium','Small',]}

In [10]:
df = pd.DataFrame(d)

In [11]:
df.head()

     sales          city    size
0   100000         Tampa   Small
1   222000         Tampa  Medium
2  1000000       Orlando   Large
3   522000  Jacksonville   Large
4   111111         Miami   Small

In [12]:
df

      sales          city    size
0    100000         Tampa   Small
1    222000         Tampa  Medium
2   1000000       Orlando   Large
3    522000  Jacksonville   Large
4    111111         Miami   Small
5    222222  Jacksonville  Medium
6   1111111         Miami   Large
7     20000         Miami   Small
8     75000       Orlando  Medium
9     90000       Orlando  Medium
10  1000000       Orlando  Medium
11    10000       Orlando   Small

In [13]:
# Here city is a nominal data so use One hot encoder

In [14]:
df["city"].unique()

array(['Tampa', 'Orlando', 'Jacksonville', 'Miami'], dtype=object)

In [15]:
from sklearn.preprocessing import OneHotEncoder

### Call one Hot encoder & ignore unknown values and change it in pandas df

In [18]:
Oh_en = OneHotEncoder(handle_unknown = "ignore",sparse_output = False).set_output(transform = 'pandas')

In [19]:
ohetransform = Oh_en.fit_transform(df[['city']])

In [20]:
ohetransform

    city_Jacksonville  city_Miami  city_Orlando  city_Tampa
0                 0.0         0.0           0.0         1.0
1                 0.0         0.0           0.0         1.0
2                 0.0         0.0           1.0         0.0
3                 1.0         0.0           0.0         0.0
4                 0.0         1.0           0.0         0.0
5                 1.0         0.0           0.0         0.0
6                 0.0         1.0           0.0         0.0
7                 0.0         1.0           0.0         0.0
8                 0.0         0.0           1.0         0.0
9                 0.0         0.0           1.0         0.0
10                0.0         0.0           1.0         0.0
11                0.0         0.0           1.0         0.0

In [21]:
df.head()

     sales          city    size
0   100000         Tampa   Small
1   222000         Tampa  Medium
2  1000000       Orlando   Large
3   522000  Jacksonville   Large
4   111111         Miami   Small

In [22]:
df = pd.concat([df,ohetransform],axis = 1).drop(columns = ['city'])

In [23]:
df.head()

     sales    size  city_Jacksonville  city_Miami  city_Orlando  city_Tampa
0   100000   Small                0.0         0.0           0.0         1.0
1   222000  Medium                0.0         0.0           0.0         1.0
2  1000000   Large                0.0         0.0           1.0         0.0
3   522000   Large                1.0         0.0           0.0         0.0
4   111111   Small                0.0         1.0           0.0         0.0